# Generated by Django 2.1.7 on 2019-03-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0002_suggestionvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='votes',
            field=models.TextField(default=[20]),
            preserve_default=False,
        ),
    ]
